version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    environment:
      NODE_ENV: "development"
      HOST: "192.168.0.100"
      PORT: 8000
    volumes:
      - /usr/app/node_modules
      - .:/usr/app:rw
    expose:
      - 8000
    ports:
      - 80:8000
    command: npm run dev
